# Generated by Django 3.2.3 on 2021-05-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('customer_fullname', models.CharField(max_length=20)),
                ('customer_email', models.CharField(max_length=20)),
                ('customer_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
