# Generated by Django 3.2.3 on 2021-05-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magictym', '0002_auto_20210515_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Billing_Address',
            field=models.CharField(default='Street 1', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='Billing_Address_State',
            field=models.CharField(default='Delhi', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='Billing_Address_ZipCode',
            field=models.CharField(default='110001', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='Billing_Address_city',
            field=models.CharField(default='road', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='Billing_Address_country',
            field=models.CharField(default='India', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='Remarks',
            field=models.TextField(default='any remarks', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='Shipping_Address',
            field=models.CharField(default='Street 1', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='Shipping_Address_State',
            field=models.CharField(default='Delhi', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='Shipping_Address_ZipCode',
            field=models.CharField(default='110001', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='Shipping_Address_city',
            field=models.CharField(default='Delhi', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='Shipping_Address_country',
            field=models.CharField(default='India', max_length=20),
        ),
    ]
